// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT0NC2z5ysg8o57KeJ5iHP7J0NeHsYxvA',
    appId: '1:443883261881:web:8d578d06122a9c4c7db068',
    messagingSenderId: '443883261881',
    projectId: 'flutter-chat-app-75c3b',
    authDomain: 'flutter-chat-app-75c3b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-75c3b.appspot.com',
    measurementId: 'G-6XM9ENGCJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKEsK_SZ27xWTfg2xdfZB7jvAlATFWSmk',
    appId: '1:443883261881:android:9d7422dc9ef3ac777db068',
    messagingSenderId: '443883261881',
    projectId: 'flutter-chat-app-75c3b',
    storageBucket: 'flutter-chat-app-75c3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl_y1MhmzMsJRu9Tf90c0EU6_KO0zMHgU',
    appId: '1:443883261881:ios:8b7224006f04ef747db068',
    messagingSenderId: '443883261881',
    projectId: 'flutter-chat-app-75c3b',
    storageBucket: 'flutter-chat-app-75c3b.appspot.com',
    iosClientId: '443883261881-32ku3qq9t5a19c40hnbvgv4pnd4loeb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl_y1MhmzMsJRu9Tf90c0EU6_KO0zMHgU',
    appId: '1:443883261881:ios:8b7224006f04ef747db068',
    messagingSenderId: '443883261881',
    projectId: 'flutter-chat-app-75c3b',
    storageBucket: 'flutter-chat-app-75c3b.appspot.com',
    iosClientId: '443883261881-32ku3qq9t5a19c40hnbvgv4pnd4loeb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
